package com.github.jinahya.hello.api._java_sql;

import com.github.jinahya.hello.api.HelloWorld;
import com.github.jinahya.hello.api.HelloWorldTest;
import com.github.jinahya.hello.api.HelloWorldTestUtils;
import lombok.AccessLevel;
import lombok.NoArgsConstructor;
import lombok.extern.slf4j.Slf4j;
import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Nested;
import org.junit.jupiter.api.Test;
import org.mockito.ArgumentMatchers;
import org.mockito.Mockito;

import java.io.ByteArrayInputStream;
import java.io.IOException;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.SQLException;

@NoArgsConstructor(access = AccessLevel.PACKAGE)
@Slf4j
class HelloWorld_SetBinaryStream_PreparedStatement_ParameterIndex__Test
        extends HelloWorldTest {

    @BeforeEach
    void __() throws SQLException {
        Mockito.doAnswer(invocation -> {
            final var ps = invocation.getArgument(0, PreparedStatement.class);
            final var pi = invocation.getArgument(1, Integer.class);
            ps.setBinaryStream(
                    pi,
                    new ByteArrayInputStream(HelloWorldTestUtils.hello_world_byte_array())
            );
            return ps;
        }).when(service()).setBinaryStream(
                ArgumentMatchers.notNull(),
                ArgumentMatchers.intThat(v -> v >= 1)
        );
        HelloWorldTestUtils.set_array_returns_the_array(service());
    }

    // -----------------------------------------------------------------------------------------------------------------
    @Nested
    class H2_Test {

        private static final String URL = "jdbc:h2:mem:setbinarystream_testdb;DB_CLOSE_DELAY=-1";

        private static final String USER = "sa";

        private static final String PASSWORD = "";

        private static final String TABLE = "hello_world";

        private static final String COLUMN = "bytes";

        @Test
        void __() throws IOException, SQLException {
            try (var connection = DriverManager.getConnection(URL, USER, PASSWORD)) {
                {
                    final var sql = """
                            CREATE TABLE %s (
                                id BIGINT PRIMARY KEY AUTO_INCREMENT,
                                %s VARBINARY(%d)
                            )"""
                            .formatted(TABLE, COLUMN, HelloWorld.BYTES);
                    try (var statement = connection.createStatement()) {
                        final var result = statement.executeUpdate(sql);
                        assert result == 0;
                    }
                }
                {
                    final var sql = "INSERT INTO %s (%s) VALUES (?)".formatted(TABLE, COLUMN);
                    try (var statement = connection.prepareStatement(sql)) {
                        service().setBinaryStream(statement, 1);
                        final var result = statement.executeUpdate();
                        assert result == 1;
                    }
                }
                {
                    final var sql = "SELECT * FROM %s".formatted(TABLE);
                    try (var statement = connection.createStatement();
                         var resultSet = statement.executeQuery(sql)) {
                        Assertions.assertTrue(resultSet.next());
                        try (var stream = resultSet.getBinaryStream(COLUMN)) {
                            Assertions.assertNotNull(stream);
                            final var bytes = stream.readAllBytes();
                            Assertions.assertEquals(HelloWorld.BYTES, bytes.length);
                            Assertions.assertArrayEquals(
                                    HelloWorldTestUtils.hello_world_byte_array(),
                                    bytes
                            );
                        }
                    }
                }
            }
        }
    }

    @Nested
    class Hsql_Test {

        private static final String URL = "jdbc:hsqldb:mem:setbinarystream_testdb";

        private static final String USER = "SA";

        private static final String PASSWORD = "";

        private static final String TABLE = "hello_world";

        private static final String COLUMN = "bytes";

        @Test
        void __() throws IOException, SQLException {
            try (var connection = DriverManager.getConnection(URL, USER, PASSWORD)) {
                {
                    final var sql = """
                            CREATE TABLE %s (
                                id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                %s VARBINARY(%d)
                            )"""
                            .formatted(TABLE, COLUMN, HelloWorld.BYTES);
                    try (var statement = connection.createStatement()) {
                        final var result = statement.executeUpdate(sql);
                        assert result == 0;
                    }
                }
                {
                    final var sql = "INSERT INTO %s (%s) VALUES (?)".formatted(TABLE, COLUMN);
                    try (var statement = connection.prepareStatement(sql)) {
                        service().setBinaryStream(statement, 1);
                        final var result = statement.executeUpdate();
                        assert result == 1;
                    }
                }
                {
                    final var sql = "SELECT * FROM %s".formatted(TABLE);
                    try (var statement = connection.createStatement();
                         var resultSet = statement.executeQuery(sql)) {
                        Assertions.assertTrue(resultSet.next());
                        try (var stream = resultSet.getBinaryStream(COLUMN)) {
                            Assertions.assertNotNull(stream);
                            final var bytes = stream.readAllBytes();
                            Assertions.assertEquals(HelloWorld.BYTES, bytes.length);
                            Assertions.assertArrayEquals(
                                    HelloWorldTestUtils.hello_world_byte_array(),
                                    bytes
                            );
                        }
                    }
                }
            }
        }
    }

    @Nested
    class SQLite_Test {

        private static final String URL = "jdbc:sqlite::memory:";

        private static final String USER = "";

        private static final String PASSWORD = "";

        private static final String TABLE = "hello_world";

        private static final String COLUMN = "bytes";

        @Test
        void __() throws IOException, SQLException {
            try (var connection = DriverManager.getConnection(URL, USER, PASSWORD)) {
                {
                    final var sql = """
                            CREATE TABLE %s (
                                id INTEGER PRIMARY KEY AUTOINCREMENT,
                                %s VARBINARY(%d)
                            )"""
                            .formatted(TABLE, COLUMN, HelloWorld.BYTES);
                    try (var statement = connection.createStatement()) {
                        final var result = statement.executeUpdate(sql);
                        assert result == 0;
                    }
                }
                {
                    final var sql = "INSERT INTO %s (%s) VALUES (?)".formatted(TABLE, COLUMN);
                    try (var statement = connection.prepareStatement(sql)) {
                        service().setBinaryStream(statement, 1);
                        final var result = statement.executeUpdate();
                        assert result == 1;
                    }
                }
                {
                    final var sql = "SELECT * FROM %s".formatted(TABLE);
                    try (var statement = connection.createStatement();
                         var resultSet = statement.executeQuery(sql)) {
                        Assertions.assertTrue(resultSet.next());
                        try (var stream = resultSet.getBinaryStream(COLUMN)) {
                            Assertions.assertNotNull(stream);
                            final var bytes = stream.readAllBytes();
                            Assertions.assertEquals(HelloWorld.BYTES, bytes.length);
                            Assertions.assertArrayEquals(
                                    HelloWorldTestUtils.hello_world_byte_array(),
                                    bytes
                            );
                        }
                    }
                }
            }
        }
    }
}
